name: Sync Fork with Upstream

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/ORIGINAL_OWNER/ORIGINAL_REPO.git || true
          git fetch upstream

      - name: Merge upstream/main into main
        run: |
          git checkout main
          git merge --no-edit upstream/main || (git status && exit 1)

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin main
